class Light {}
class Dress {}
class Disc {}
class Button {}
class Chocolate {}
class Logo {}
class Coin {}
class Borewell {}
class Robot {}
class IronBox {}
class Wood {}
class Plastic {}
class NumberPlate {}
class Cotton {}
class SkateBoard {}
class ToothPaste {}
class Tom {}
class Jerry {}
