class GreenLineMetroStations {
    public static void main(String[] args) {
        String name1 = "Madavara";
        String name2 = "Chikkabidarakallu";
        String name3 = "Manjunathanagara";
        String name4 = "Peenya Industry";
        String name5 = "Peenya";
        String name6 = "Goraguntepalya";
        String name7 = "Yeshwanthpura";
        String name8 = "Sandal Soap Factory";
        String name9 = "Nag​​asandra";
        String name10 = "Dasarahalli";
        String name11 = "Jalahalli";
        String name12 = "Mahalakshmi";
        String name13 = "Rajajinagara";
        String name14 = "Mahakavi Kuvempu Road";
        String name15 = "Srirampura";
        String name16 = "Sampige Road";
        String name17 = "Nadaprabhu Kempegowda Station";
        String name18 = "Chikpete";
        String name19 = "Yelachenahalli";
        String name20 = "Konanakunte Cross";
        String name21 = "Doddakallasandra";
        String name22 = "Krishna Rajendra Market";
        String name23 = "National College";
        String name24 = "Lalbagh Botanical Garden";
        String name25 = "South End Circle";
        String name26 = "Jayanagar";
        String name27 = "Rashtreeya Vidyalaya Road";
        String name28 = "Banashankari";
        String name29 = "Jaya Prakash Nagar";
        String name30 = "Vajarahalli";
        String name31 = "Thalaghattapura";
        String name32 = "Silk Institute";

        System.out.println("1. " + name1);
        System.out.println("2. " + name2);
        System.out.println("3. " + name3);
        System.out.println("4. " + name4);
        System.out.println("5. " + name5);
        System.out.println("6. " + name6);
        System.out.println("7. " + name7);
        System.out.println("8. " + name8);
        System.out.println("9. " + name9);
        System.out.println("10. " + name10);
        System.out.println("11. " + name11);
        System.out.println("12. " + name12);
        System.out.println("13. " + name13);
        System.out.println("14. " + name14);
        System.out.println("15. " + name15);
        System.out.println("16. " + name16);
        System.out.println("17. " + name17);
        System.out.println("18. " + name18);
        System.out.println("19. " + name19);
        System.out.println("20. " + name20);
        System.out.println("21. " + name21);
        System.out.println("22. " + name22);
        System.out.println("23. " + name23);
        System.out.println("24. " + name24);
        System.out.println("25. " + name25);
        System.out.println("26. " + name26);
        System.out.println("27. " + name27);
        System.out.println("28. " + name28);
        System.out.println("29. " + name29);
        System.out.println("30. " + name30);
        System.out.println("31. " + name31);
        System.out.println("32. " + name32);
    }
}
