class PuneethRajkumarMovies {
    public static void main(String[] args) {
        String name1 = "Bettada Hoovu";
        String name2 = "Yarivanu";
        String name3 = "Eradu Nakshatragalu";
        String name4 = "Bhakta Prahlada";
        String name5 = "Shiva Mecchida Kannappa";
        String name6 = "Parashuram";
        String name7 = "Appu";
        String name8 = "Abhi";
        String name9 = "Veera Kannadiga";
        String name10 = "Maurya";
        String name11 = "Aakash";
        String name12 = "Namma Basava";
        String name13 = "Ajay";
        String name14 = "Arasu";
        String name15 = "Milana";
        String name16 = "Vamshi";
        String name17 = "Bindass";
        String name18 = "Raaj – The Showman";
        String name19 = "Raam";
        String name20 = "Prithvi";
        String name21 = "Jackie";
        String name22 = "Hudugaru";
        String name23 = "Paramathma";
        String name24 = "Anna Bond";
        String name25 = "Yaare Koogadali";
        String name26 = "Ninnindale";
        String name27 = "Power";
        String name28 = "Mythri";
        String name29 = "Rana Vikrama";
        String name30 = "Doddmane Hudga";
        String name31 = "Raajakumara";
        String name32 = "Anjani Putra";
        String name33 = "Humble Politician Nograj";
        String name34 = "Natasaarvabhowma";
        String name35 = "Kavaludaari";
        String name36 = "Yuvarathnaa";
        String name37 = "Gandhada Gudi";
        String name38 = "Lucky Man";
        String name39 = "James";
        String name40 = "Padde Huli";
        String name41 = "Mayabazar 2016";
        String name42 = "Rajaratha";
        String name43 = "Powerstar";
        String name44 = "Veera Madakari";

        System.out.println("1. " + name1);
        System.out.println("2. " + name2);
        System.out.println("3. " + name3);
        System.out.println("4. " + name4);
        System.out.println("5. " + name5);
        System.out.println("6. " + name6);
        System.out.println("7. " + name7);
        System.out.println("8. " + name8);
        System.out.println("9. " + name9);
        System.out.println("10. " + name10);
        System.out.println("11. " + name11);
        System.out.println("12. " + name12);
        System.out.println("13. " + name13);
        System.out.println("14. " + name14);
        System.out.println("15. " + name15);
        System.out.println("16. " + name16);
        System.out.println("17. " + name17);
        System.out.println("18. " + name18);
        System.out.println("19. " + name19);
        System.out.println("20. " + name20);
        System.out.println("21. " + name21);
        System.out.println("22. " + name22);
        System.out.println("23. " + name23);
        System.out.println("24. " + name24);
        System.out.println("25. " + name25);
        System.out.println("26. " + name26);
        System.out.println("27. " + name27);
        System.out.println("28. " + name28);
        System.out.println("29. " + name29);
        System.out.println("30. " + name30);
        System.out.println("31. " + name31);
        System.out.println("32. " + name32);
        System.out.println("33. " + name33);
        System.out.println("34. " + name34);
        System.out.println("35. " + name35);
        System.out.println("36. " + name36);
        System.out.println("37. " + name37);
        System.out.println("38. " + name38);
        System.out.println("39. " + name39);
        System.out.println("40. " + name40);
        System.out.println("41. " + name41);
        System.out.println("42. " + name42);
        System.out.println("43. " + name43);
        System.out.println("44. " + name44);
    }
}
