class TopIndianArtists {
    public static void main(String[] args) {

     
        String name1 = "Yash";
        String name2 = "Puneeth Rajkumar";
        String name3 = "Sudeep";
        String name4 = "Darshan";
        String name5 = "Radhika Pandit";
        String name6 = "Shruti Hariharan";
        String name7 = "Rachita Ram";
        String name8 = "Ragini Dwivedi";
        String name9 = "Shivarajkumar";
        String name10 = "Upendra";
        String name11 = "Amitabh Bachchan";
        String name12 = "Shah Rukh Khan";
        String name13 = "Salman Khan";
        String name14 = "Aamir Khan";
        String name15 = "Hrithik Roshan";
        String name16 = "Ranveer Singh";
        String name17 = "Ranbir Kapoor";
        String name18 = "Akshay Kumar";
        String name19 = "Ajay Devgn";
        String name20 = "Rajinikanth";
        String name21 = "Kamal Haasan";
        String name22 = "Vijay";
        String name23 = "Allu Arjun";
        String name24 = "Mahesh Babu";
        String name25 = "Prabhas";
        String name26 = "Nani";
        String name27 = "Jr NTR";
        String name28 = "Ram Charan";
        String name29 = "Dulquer Salmaan";
        String name30 = "Fahadh Faasil";
        String name31 = "Mammootty";
        String name32 = "Mohanlal";
        String name33 = "Vicky Kaushal";
        String name34 = "Ayushmann Khurrana";
        String name35 = "Alia Bhatt";
        String name36 = "Deepika Padukone";
        String name37 = "Kangana Ranaut";
        String name38 = "Priyanka Chopra";
        String name39 = "Katrina Kaif";
        String name40 = "Anushka Sharma";
        String name41 = "Taapsee Pannu";
        String name42 = "Shraddha Kapoor";
        String name43 = "Kiara Advani";
        String name44 = "Sara Ali Khan";
        String name45 = "Janhvi Kapoor";
        String name46 = "Bhumi Pednekar";
        String name47 = "Radhika Apte";
        String name48 = "Samantha Ruth Prabhu";
        String name49 = "Nithya Menen";
        String name50 = "Trisha Krishnan";
        System.out.println("1. " + name1);
        System.out.println("2. " + name2);
        System.out.println("3. " + name3);
        System.out.println("4. " + name4);
        System.out.println("5. " + name5);
        System.out.println("6. " + name6);
        System.out.println("7. " + name7);
        System.out.println("8. " + name8);
        System.out.println("9. " + name9);
        System.out.println("10. " + name10);
        System.out.println("11. " + name11);
        System.out.println("12. " + name12);
        System.out.println("13. " + name13);
        System.out.println("14. " + name14);
        System.out.println("15. " + name15);
        System.out.println("16. " + name16);
        System.out.println("17. " + name17);
        System.out.println("18. " + name18);
        System.out.println("19. " + name19);
        System.out.println("20. " + name20);
        System.out.println("21. " + name21);
        System.out.println("22. " + name22);
        System.out.println("23. " + name23);
        System.out.println("24. " + name24);
        System.out.println("25. " + name25);
        System.out.println("26. " + name26);
        System.out.println("27. " + name27);
        System.out.println("28. " + name28);
        System.out.println("29. " + name29);
        System.out.println("30. " + name30);
        System.out.println("31. " + name31);
        System.out.println("32. " + name32);
        System.out.println("33. " + name33);
        System.out.println("34. " + name34);
        System.out.println("35. " + name35);
        System.out.println("36. " + name36);
        System.out.println("37. " + name37);
        System.out.println("38. " + name38);
        System.out.println("39. " + name39);
        System.out.println("40. " + name40);
        System.out.println("41. " + name41);
        System.out.println("42. " + name42);
        System.out.println("43. " + name43);
        System.out.println("44. " + name44);
        System.out.println("45. " + name45);
        System.out.println("46. " + name46);
        System.out.println("47. " + name47);
        System.out.println("48. " + name48);
        System.out.println("49. " + name49);
        System.out.println("50. " + name50);
    }
}
