class Vegetables {
    public static void main(String[] args) {

       
        String name1 = "Potato";
        String name2 = "Tomato";
        String name3 = "Onion";
        String name4 = "Carrot";
        String name5 = "Cabbage";
        String name6 = "Spinach";
        String name7 = "Cauliflower";
        String name8 = "Radish";
        String name9 = "Beetroot";
        String name10 = "Pumpkin";
        String name11 = "Brinjal";
        String name12 = "Ladyfinger";
        String name13 = "Chili";
        String name14 = "Garlic";
        String name15 = "Ginger";
        String name16 = "Peas";
        String name17 = "Corn";
        String name18 = "Cucumber";
        String name19 = "Bittergourd";
        String name20 = "Bottle Gourd";
        String name21 = "Ridge Gourd";
        String name22 = "Snake Gourd";
        String name23 = "Fenugreek Leaves";
        String name24 = "Drumstick";
        String name25 = "Taro";
        String name26 = "Turnip";
        String name27 = "Mushroom";
        String name28 = "Sweet Potato";
        String name29 = "Celery";
        String name30 = "Lettuce";
        String name31 = "Arbi Leaves";
        String name32 = "Amaranth Leaves";
        String name33 = "Coriander Leaves";
        String name34 = "Mint";
        String name35 = "Kohlrabi";
        String name36 = "Yam";
        String name37 = "Parwal";
        String name38 = "Palak";
        String name39 = "Cabbage Leaves";
        String name40 = "Broccoli";
        String name41 = "Zucchini";
        String name42 = "Leek";
        String name43 = "Okra";
        String name44 = "Chayote";
        String name45 = "Seaweed";
        String name46 = "Bok Choy";
        String name47 = "Watercress";
        String name48 = "Fennel";
        String name49 = "Radicchio";
        String name50 = "Collard Greens";
        String name51 = "Endive";
        String name52 = "Kale";
        String name53 = "Mustard Greens";
        String name54 = "Swiss Chard";
        String name55 = "Turnip Greens";
        String name56 = "Rutabaga";
        String name57 = "Jicama";
        String name58 = "Horseradish";
        String name59 = "Cassava";
        String name60 = "Celeriac";
        String name61 = "Parsnip";
        String name62 = "Sunchoke";
        String name63 = "Tinda";
        String name64 = "Yardlong Beans";
        String name65 = "Cluster Beans";
        String name66 = "Broad Beans";
        String name67 = "Snap Peas";
        String name68 = "Green Beans";
        String name69 = "Winged Beans";
        String name70 = "Asparagus";
        String name71 = "Artichoke";
        String name72 = "Bamboo Shoots";
        String name73 = "Chicory";
        String name74 = "Cress";
        String name75 = "Dandelion Greens";
        String name76 = "Kangkong";
        String name77 = "Lotus Root";
        String name78 = "Nopal";
        String name79 = "Radish Leaves";
        String name80 = "Sorrel";
        String name81 = "Tatsoi";
        String name82 = "Water Spinach";
        String name83 = "Bitter Leaf";
        String name84 = "Pumpkin Leaves";
        String name85 = "Amaranth Stem";
        String name86 = "Moringa Leaves";
        String name87 = "Broccolini";
        String name88 = "Baby Corn";
        String name89 = "Kohlrabi Leaves";
        String name90 = "Sweet Corn";
        String name91 = "Chili Leaves";
        String name92 = "Garlic Chives";
        String name93 = "Perilla Leaves";
        String name94 = "Nasturtium Leaves";
        String name95 = "Salsify";
        String name96 = "Oca";
        String name97 = "Malabar Spinach";
        String name98 = "Burdock Root";
        String name99 = "Ulluco";
        String name100 = "Cabbage Sprouts";
        System.out.println("1. " + name1);
        System.out.println("2. " + name2);
        System.out.println("3. " + name3);
        System.out.println("4. " + name4);
        System.out.println("5. " + name5);
        System.out.println("6. " + name6);
        System.out.println("7. " + name7);
        System.out.println("8. " + name8);
        System.out.println("9. " + name9);
        System.out.println("10. " + name10);
        System.out.println("11. " + name11);
        System.out.println("12. " + name12);
        System.out.println("13. " + name13);
        System.out.println("14. " + name14);
        System.out.println("15. " + name15);
        System.out.println("16. " + name16);
        System.out.println("17. " + name17);
        System.out.println("18. " + name18);
        System.out.println("19. " + name19);
        System.out.println("20. " + name20);
        System.out.println("21. " + name21);
        System.out.println("22. " + name22);
        System.out.println("23. " + name23);
        System.out.println("24. " + name24);
        System.out.println("25. " + name25);
        System.out.println("26. " + name26);
        System.out.println("27. " + name27);
        System.out.println("28. " + name28);
        System.out.println("29. " + name29);
        System.out.println("30. " + name30);
        System.out.println("31. " + name31);
        System.out.println("32. " + name32);
        System.out.println("33. " + name33);
        System.out.println("34. " + name34);
        System.out.println("35. " + name35);
        System.out.println("36. " + name36);
        System.out.println("37. " + name37);
        System.out.println("38. " + name38);
        System.out.println("39. " + name39);
        System.out.println("40. " + name40);
        System.out.println("41. " + name41);
        System.out.println("42. " + name42);
        System.out.println("43. " + name43);
        System.out.println("44. " + name44);
        System.out.println("45. " + name45);
        System.out.println("46. " + name46);
        System.out.println("47. " + name47);
        System.out.println("48. " + name48);
        System.out.println("49. " + name49);
        System.out.println("50. " + name50);
        System.out.println("51. " + name51);
        System.out.println("52. " + name52);
        System.out.println("53. " + name53);
        System.out.println("54. " + name54);
        System.out.println("55. " + name55);
        System.out.println("56. " + name56);
        System.out.println("57. " + name57);
        System.out.println("58. " + name58);
        System.out.println("59. " + name59);
        System.out.println("60. " + name60);
        System.out.println("61. " + name61);
        System.out.println("62. " + name62);
        System.out.println("63. " + name63);
        System.out.println("64. " + name64);
        System.out.println("65. " + name65);
        System.out.println("66. " + name66);
        System.out.println("67. " + name67);
        System.out.println("68. " + name68);
        System.out.println("69. " + name69);
        System.out.println("70. " + name70);
        System.out.println("71. " + name71);
        System.out.println("72. " + name72);
        System.out.println("73. " + name73);
        System.out.println("74. " + name74);
        System.out.println("75. " + name75);
        System.out.println("76. " + name76);
        System.out.println("77. " + name77);
        System.out.println("78. " + name78);
        System.out.println("79. " + name79);
        System.out.println("80. " + name80);
        System.out.println("81. " + name81);
        System.out.println("82. " + name82);
        System.out.println("83. " + name83);
        System.out.println("84. " + name84);
        System.out.println("85. " + name85);
        System.out.println("86. " + name86);
        System.out.println("87. " + name87);
        System.out.println("88. " + name88);
        System.out.println("89. " + name89);
        System.out.println("90. " + name90);
        System.out.println("91. " + name91);
        System.out.println("92. " + name92);
        System.out.println("93. " + name93);
        System.out.println("94. " + name94);
        System.out.println("95. " + name95);
        System.out.println("96. " + name96);
        System.out.println("97. " + name97);
        System.out.println("98. " + name98);
        System.out.println("99. " + name99);
        System.out.println("100. " + name100);
    }
}
